@echo off
echo Configurando banco Somee...
set DB_URL=jdbc:sqlserver://tccamp2.mssql.somee.com:1433;databaseName=tccamp2;encrypt=true;trustServerCertificate=true
set DB_USERNAME=Noc
set DB_PASSWORD=12345678

echo Compilando...
javac -cp "sqljdbc_13.2.0.0_ptb.zip" SimpleServer.java

echo Iniciando servidor...
echo Testando conexao...
java -cp ".;sqljdbc_13.2.0.0_ptb.zip" SimpleServer 2>&1
echo.
echo Servidor parou. Pressione qualquer tecla...
pause